burroplayer:
  path: /media
  loopPrefix: loop
  player: mplayer    # omxplayer or mplayer
  minNumber: 256
  adapter:
    PI4J:
      serial:
        comPort: /dev/ttyAMA0
        baud: 4800
        controllBytes:
          startRange: 0
          endRange: 10
          pause: 130
          stop: 128
          status: 129
        sendingBytes:
          playerRunning: 128
          playerNotRunning: 0
      pins:
        happening: GPIO 5
        moviestatus: GPIO 4
    filechecker:
      cyclic: true
      seconds: 60

omxplayer:
  exe: /usr/bin/omxplayer
  options: -o both
  pause: p


logging:
#    file: /var/burrotinto/burro.log
    level:
#        org.springframework: 'OFF'
#        de.burrotinto: 'OFF'
#        com.pi4j: 'OFF'
